image: maven:3.6.3

definitions:
  steps:
    - step: &build
        name: Build and Test
        caches:
          - maven
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - mvn clean install
        services:
          - docker
        artifacts:
          - target/*
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.2.0
    - step: &security_scan
        name: Security Scan
        script:
          # Run a security scan for sensitive data.
          # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
          - pipe: atlassian/git-secrets-scan:0.4.3
  services:
    docker:
      memory: 2048
pipelines:
  default:
    - parallel:
      - step: *build
      - step: *security_scan
  branches:
    master:
      - parallel:
        - step: *build
        - step: *security_scan
      - step:
          name: Deploy to testing
          deployment: test
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: 'target/$APPLICATION_NAME-$version.jar'
                WAIT_INTERVAL: 60
                WARMUP_INTERVAL: 30
                WAIT: 'true'
